name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Destino (dev/qa/prod)"
        required: true
        default: dev
      version:
        description: "Tag/version a promover (e.g. v0.1.0)"
        required: false

jobs:
  deploy_dev:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: migrate-sql
          path: artifacts
        continue-on-error: true

      - name: TODO - Run DB migrations (Dev)
        run: |
          echo "Future: run artifacts/migrate.sql against ChetangoDB_Dev"

      - name: TODO - Publish API (Dev)
        run: |
          echo "Future: deploy to Azure/App Service"

      - name: TODO - Smoke tests (Dev)
        run: |
          echo "Future: GET /health && GET /ready"

  deploy_qa:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'qa'
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TODO - Promote to QA
        run: |
          echo "Future: use tag '${{ github.event.inputs.version }}'"
          echo "Future: run migrate.sql on ChetangoDB_QA"
          echo "Future: publish API QA"
          echo "Future: smoke tests"

  deploy_prod:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TODO - Promote to PROD
        run: |
          echo "Future: use tag '${{ github.event.inputs.version }}'"
          echo "Future: run migrate.sql on ChetangoDB_Prod"
          echo "Future: publish API Prod"
          echo "Future: smoke tests"






