name: CD

on:
  push:
    branches: [ main ]   # Dev autom치tico al hacer merge a main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Destino del despliegue"
        required: true
        options: [dev, qa, prod]
      version:
        description: "Tag/versi칩n a promover (ej: v0.1.0)"
        required: false

jobs:
  deploy_dev:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: TODO - Descargar artefactos de build (si existen)
        uses: actions/download-artifact@v4
        with:
          name: migrate-sql
          path: artifacts
        continue-on-error: true
      - name: TODO - Ejecutar migraciones Dev
        run: echo "Futuro: ejecutar artifacts/migrate.sql contra ChetangoDB_Dev"
      - name: TODO - Publicar API en Dev
        run: echo "Futuro: deploy a Azure/App Service"
      - name: TODO - Smoke tests
        run: echo "Futuro: GET /health y /ready"

  deploy_qa:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'qa'
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v4
      - name: TODO - Promover versi칩n a QA
        run: |
          echo "Futuro: usar tag '${{ github.event.inputs.version }}'"
          echo "Futuro: ejecutar migrate.sql en ChetangoDB_QA"
          echo "Futuro: publicar API QA"
          echo "Futuro: smoke tests"

  deploy_prod:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: TODO - Promover versi칩n a PROD
        run: |
          echo "Futuro: usar tag '${{ github.event.inputs.version }}'"
          echo "Futuro: ejecutar migrate.sql en ChetangoDB_Prod"
          echo "Futuro: publicar API Prod"
          echo "Futuro: smoke tests"
